### ISSUE TITLE
Bayonets Attach to MP40's

### ISSUE THREAD

**Issue by Wesreidau** [kachnov/WW13#123]
Currently bayonets attach to MP40s, and I would presume any other gun. They need to be restricted to those specific weapons with bayonet lugs; the Kar98k and the Mosin.

In the future this may need to be further defined as German and Russian bayonets attaching only to their respective rifles.

**Comment by MrJJJ2** [comment]
They also can be attached to Luger pistol, and possibly the soviet pistol that i forgot name of.

**Comment by chesse20** [comment]
not a bug i think you can just stick knifes on any gun in real life so its fine i think
