### ISSUE TITLE
Flammenwerfer throws too much flammen

### ISSUE THREAD

**Issue by OPacity2** [kachnov/WW13#133]
The flammenwerfer at 60 output covers almost the whole screen in flames. While flamethrowers are devastating, I don't think they're that bad.

**Comment by OPacity2** [comment]
And, uh, sorry if this isn't set up right, I dunno how to do this github stuff.

**Comment by kachnov** [comment]
yeah, this is good

**Comment by tylerh95** [comment]
Duplicate of #42
