### ISSUE TITLE
Give Command roles an Officer's Cap

### ISSUE THREAD

**Issue by Difrit** [kachnov/WW13#168]
Helps to mark them out as a leader so both the SS and Wehrmacht can follow them.

Gives the Russians a bonus target.

Command roles defined as Gruppenfuhrers/SS leader/Russian squad leaders etc

**Comment by kachnov** [comment]
gruppenfuhrer should already have it

**Comment by Difrit** [comment]
I believe the Gruppenfuhrer spawns with a helmet. I may be mistaken though, because nobody ever plays them because they're worthless.
