### ISSUE TITLE
Snipers.

### ISSUE THREAD

**Issue by UnarmedBastard** [kachnov/WW13#174]
Dawned on me german snipers have easily 2 tiles + on the russian model when I kept getting shot from the same direction I was looking at through my scope.
Maybe this made sense when you couldn't stay scoped in all the time and germans had to push into russian scope range, but this isn't the case anymore. Germans can push while scoped in, and have every advantage.

Since range is everything, this basically means russian snipers are supposed to lose sniper duels *except* if they push aggressively, (and even then, range is everything) when they are supposed to be defenders.

**Comment by Difrit** [comment]
Can confirm.
