### ISSUE TITLE
The barrier is broken?

### ISSUE THREAD

**Issue by NobodyNotable** [kachnov/WW13#68]
I think the barrier may or may not be broken in some places, as right after the germans arrived one round (The peace period was not even close to being over yet) there was a Russian running around near the river, here and casually murdering the germans.
![nml bug](https://user-images.githubusercontent.com/30012351/27994416-dc291906-64b5-11e7-89ce-67c8346f4bf4.png)

**Comment by tylerh95** [comment]
Adding on, I've heard you can destroy defenders by destroying a wall it is on.
