### ISSUE TITLE
Minor map edits

### ISSUE THREAD

**Issue by Chuckachu** [kachnov/WW13#73]
If you have the time. Minor changes, Rearranged both sets of medical bays to put in a sink. Added a second Combat medicine medic kit in their supply, Put early roadsigns in the German base to hopefully lead people towards the train.

https://drive.google.com/file/d/0BwmUelftcbhScS05WERtUzZZcWM/view?usp=sharing

**Comment by tylerh95** [comment]
@Chuckachu why did you close this? Just curious.

**Comment by Soundwavesghost** [comment]
I made a error on the map and then instead of fixing this one I just waited until I had a more polished version to upload.
