### ISSUE TITLE
Zavhoz(and probably other roles that speak two languages) spawn in with a German character.

### ISSUE THREAD

**Issue by TeknoKot** [kachnov/WW13#77]
Whenever you join as Zavhoz, it automatically uses your German character instead of the Russian one, my guess is because it has been preset as a German only role.

**Comment by martinlyra** [comment]
A quick search using Github's function has brought me to this conclusion:
Unlike other Soviet roles, German is the first language to be added their character and default language is misspelled as `Rusian` instead of `Russian`

**Comment by kachnov** [comment]
probably fixed in the next build
