### ISSUE TITLE
People can go through mercy period lines.

### ISSUE THREAD

**Issue by TeknoKot** [kachnov/WW13#78]
People are able to pass through the line that holds people back from going deep into another base since round start, they can climb a crate over that is behind the line or get someone to push you with help intent over it.

**Comment by tylerh95** [comment]
Needs testing, but I've heard it can also be done by breaking a wall or other structure that is on the same tile as the mercy thing.

**Comment by Difrit** [comment]
Can also be done by pulling someone and moving them onto the tile with the invisible wall.

**Comment by Wesreidau** [comment]
The mercy period lines have been made multiple tiles thick as of 7/12. #

**Comment by tylerh95** [comment]
Should be fixed.
