### ISSUE TITLE
Sandbags block non-projectile objects from entering their tile

### ISSUE THREAD

**Issue by martinlyra** [kachnov/WW13#92]
Although crates are not affected by the sandbags, what I've seen so far.

Reproduction:
1. Pick a random object, be it a rifle or alike.
2. Pull it
3. Walk along a wall of sandbags.
4. Observe how the object does not enter the last previous tile you had entered.

I had observed this during a debug test of the Maxim machine guns.

**Comment by Supermichael777** [comment]
working on a fix my problem now is that objects can move over sandbags

**Comment by Bernhaben** [comment]
What if you just added a separate check for objects that will prevent them from entering the tile the sandbags are on? Like a flag or something. Also, can you make it so that grenades have a chance at going over sandbags?
