### ISSUE TITLE
Players on moving trains can ignore doors (and possibly walls)

### ISSUE THREAD

**Issue by Hate9** [kachnov/WW13#93]
When a player is on a moving train, they can ignore a closed door in the direction the train is moving in relation to them (and probably walls).
For an example, if the player is on a train moving downwards, and they move to a door (or probably wall) below them, they ignore it.

**Comment by martinlyra** [comment]
I've observed this issue happening only when I e.g. try to walk upwards when the train is moving upwards, I become fast enough to move to the tile behind the door. Confirming this as a major issue

**Comment by tylerh95** [comment]
Should be fixes
